from app.core.database import SessionLocal, Base, engine
from app.models.product import Product

Base.metadata.create_all(bind=engine)

products = [
    {
        "name": "Sony WH-CH720N",
        "slug": "sony-wh-ch720n",
        "brand": "Sony",
        "main_category": "Wireless",
        "sub_category": "Over-Ear",
        "price": 9990,
        "original_price": 11990,
        "rating": 4.6,
        "review_count": 1284,
        "stock": 12,
        "featured": True,
        "best_seller": True,
        "use_case": "Music, Calls, Travel",
        "noise_cancellation": True,
        "battery_life": "35h",
        "connectivity": "Bluetooth 5.2",
        "mic": True,
        "color": "Black",
        "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80",
        "description": "A premium headphone designed for immersive music, calls, and modern everyday listening."
    },
    {
        "name": "JBL Tune 770NC",
        "slug": "jbl-tune-770nc",
        "brand": "JBL",
        "main_category": "Wireless",
        "sub_category": "Over-Ear",
        "price": 8499,
        "original_price": 9999,
        "rating": 4.5,
        "review_count": 944,
        "stock": 7,
        "featured": True,
        "best_seller": True,
        "use_case": "Music, Travel, Daily Use",
        "noise_cancellation": True,
        "battery_life": "50h",
        "connectivity": "Bluetooth 5.3",
        "mic": True,
        "color": "Blue",
        "image": "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80",
        "description": "Balanced sound, long battery life, and active noise cancellation for modern daily listening."
    },
    {
        "name": "boAt Nirvana 751 ANC",
        "slug": "boat-nirvana-751-anc",
        "brand": "boAt",
        "main_category": "Wireless",
        "sub_category": "Over-Ear",
        "price": 3999,
        "original_price": 7990,
        "rating": 4.3,
        "review_count": 2150,
        "stock": 22,
        "featured": True,
        "best_seller": False,
        "use_case": "Music, Calls",
        "noise_cancellation": True,
        "battery_life": "65h",
        "connectivity": "Bluetooth 5.0",
        "mic": True,
        "color": "Silver",
        "image": "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80",
        "description": "A feature-rich wireless headphone with ANC and long battery life for immersive sessions."
    },
    {
        "name": "Noise Two Wireless",
        "slug": "noise-two-wireless",
        "brand": "Noise",
        "main_category": "Wireless",
        "sub_category": "Over-Ear",
        "price": 2499,
        "original_price": 3499,
        "rating": 4.1,
        "review_count": 612,
        "stock": 16,
        "featured": False,
        "best_seller": False,
        "use_case": "Calls, Daily Use",
        "noise_cancellation": False,
        "battery_life": "50h",
        "connectivity": "Bluetooth 5.3",
        "mic": True,
        "color": "Green",
        "image": "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=900&q=80",
        "description": "An affordable wireless option for daily calls, casual music, and long usage hours."
    },
    {
        "name": "OnePlus Bullets Wireless Z2",
        "slug": "oneplus-bullets-wireless-z2",
        "brand": "OnePlus",
        "main_category": "Wireless",
        "sub_category": "Neckband",
        "price": 1999,
        "original_price": 2299,
        "rating": 4.4,
        "review_count": 3075,
        "stock": 30,
        "featured": False,
        "best_seller": True,
        "use_case": "Calls, Workout, Daily Use",
        "noise_cancellation": False,
        "battery_life": "30h",
        "connectivity": "Bluetooth 5.0",
        "mic": True,
        "color": "Black",
        "image": "https://images.unsplash.com/photo-1578319439584-104c94d37305?auto=format&fit=crop&w=900&q=80",
        "description": "Lightweight neckband audio built for comfort, calls, workouts, and all-day use."
    },
    {
        "name": "JBL C100SI",
        "slug": "jbl-c100si",
        "brand": "JBL",
        "main_category": "Wired",
        "sub_category": "In-Ear",
        "price": 699,
        "original_price": 1299,
        "rating": 4.2,
        "review_count": 5199,
        "stock": 48,
        "featured": False,
        "best_seller": True,
        "use_case": "Music, Calls",
        "noise_cancellation": False,
        "battery_life": "N/A",
        "connectivity": "3.5mm Jack",
        "mic": True,
        "color": "Red",
        "image": "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80",
        "description": "A budget wired in-ear choice with clear sound and mic support for everyday use."
    },
    {
        "name": "Sony MDR-ZX110A",
        "slug": "sony-mdr-zx110a",
        "brand": "Sony",
        "main_category": "Wired",
        "sub_category": "On-Ear",
        "price": 999,
        "original_price": 1490,
        "rating": 4.1,
        "review_count": 2014,
        "stock": 19,
        "featured": False,
        "best_seller": False,
        "use_case": "Music, Daily Use",
        "noise_cancellation": False,
        "battery_life": "N/A",
        "connectivity": "3.5mm Jack",
        "mic": False,
        "color": "White",
        "image": "https://images.unsplash.com/photo-1519677100203-a0e668c92439?auto=format&fit=crop&w=900&q=80",
        "description": "A lightweight wired on-ear headphone suitable for casual music and daily listening."
    },
    {
        "name": "boAt BassHeads 100",
        "slug": "boat-bassheads-100",
        "brand": "boAt",
        "main_category": "Wired",
        "sub_category": "In-Ear",
        "price": 499,
        "original_price": 999,
        "rating": 4.0,
        "review_count": 8400,
        "stock": 55,
        "featured": False,
        "best_seller": True,
        "use_case": "Music, Calls",
        "noise_cancellation": False,
        "battery_life": "N/A",
        "connectivity": "3.5mm Jack",
        "mic": True,
        "color": "Black",
        "image": "https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?auto=format&fit=crop&w=900&q=80",
        "description": "An entry-level wired earphone with punchy sound and convenient inline microphone."
    },
    {
        "name": "Redgear Cosmo 7.1",
        "slug": "redgear-cosmo-7-1",
        "brand": "Redgear",
        "main_category": "Wired",
        "sub_category": "Gaming Headset",
        "price": 1799,
        "original_price": 2999,
        "rating": 4.3,
        "review_count": 1521,
        "stock": 9,
        "featured": True,
        "best_seller": False,
        "use_case": "Gaming, Calls",
        "noise_cancellation": False,
        "battery_life": "N/A",
        "connectivity": "USB / 3.5mm",
        "mic": True,
        "color": "Black",
        "image": "https://images.unsplash.com/photo-1612444530582-fc66183b16f7?auto=format&fit=crop&w=900&q=80",
        "description": "A wired gaming headset with immersive audio, mic support, and comfortable fit."
    },
    {
        "name": "EKSA E900 Pro",
        "slug": "eksa-e900-pro",
        "brand": "EKSA",
        "main_category": "Wired",
        "sub_category": "Gaming Headset",
        "price": 2399,
        "original_price": 3499,
        "rating": 4.4,
        "review_count": 611,
        "stock": 5,
        "featured": True,
        "best_seller": False,
        "use_case": "Gaming, Streaming",
        "noise_cancellation": False,
        "battery_life": "N/A",
        "connectivity": "3.5mm Jack",
        "mic": True,
        "color": "Black / Blue",
        "image": "https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=900&q=80",
        "description": "A gaming-focused wired headset designed for streaming, team chat, and low-latency play."
    },
]


def run():
    db = SessionLocal()
    try:
        existing = db.query(Product).count()
        if existing > 0:
            print("Products already seeded.")
            return

        for item in products:
            db.add(Product(**item))
        db.commit()
        print("Seeded products successfully.")
    finally:
        db.close()


if __name__ == "__main__":
    run()
