export type Product = {
  id: number;
  name: string;
  slug: string;
  brand: string;
  mainCategory: "Wired" | "Wireless";
  subCategory: string;
  price: number;
  originalPrice: number;
  rating: number;
  reviewCount: number;
  stock: number;
  featured: boolean;
  bestSeller: boolean;
  useCase: string[];
  noiseCancellation: boolean;
  batteryLife: string;
  connectivity: string;
  mic: boolean;
  color: string;
  image: string;
  description: string;
};

export const products: Product[] = [
  {
    id: 1,
    name: "Sony WH-CH720N",
    slug: "sony-wh-ch720n",
    brand: "Sony",
    mainCategory: "Wireless",
    subCategory: "Over-Ear",
    price: 9990,
    originalPrice: 11990,
    rating: 4.6,
    reviewCount: 1284,
    stock: 12,
    featured: true,
    bestSeller: true,
    useCase: ["Music", "Calls", "Travel"],
    noiseCancellation: true,
    batteryLife: "35h",
    connectivity: "Bluetooth 5.2",
    mic: true,
    color: "Black",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80",
    description: "A premium headphone designed for immersive music, calls, and modern everyday listening.",
  },
  {
    id: 2,
    name: "JBL Tune 770NC",
    slug: "jbl-tune-770nc",
    brand: "JBL",
    mainCategory: "Wireless",
    subCategory: "Over-Ear",
    price: 8499,
    originalPrice: 9999,
    rating: 4.5,
    reviewCount: 944,
    stock: 7,
    featured: true,
    bestSeller: true,
    useCase: ["Music", "Travel", "Daily Use"],
    noiseCancellation: true,
    batteryLife: "50h",
    connectivity: "Bluetooth 5.3",
    mic: true,
    color: "Blue",
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80",
    description: "A premium headphone designed for immersive music, calls, and modern everyday listening.",
  },
  {
    id: 3,
    name: "boAt Nirvana 751 ANC",
    slug: "boat-nirvana-751-anc",
    brand: "boAt",
    mainCategory: "Wireless",
    subCategory: "Over-Ear",
    price: 3999,
    originalPrice: 7990,
    rating: 4.3,
    reviewCount: 2150,
    stock: 22,
    featured: true,
    bestSeller: false,
    useCase: ["Music", "Calls"],
    noiseCancellation: true,
    batteryLife: "65h",
    connectivity: "Bluetooth 5.0",
    mic: true,
    color: "Silver",
    image: "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80",
    description: "A premium headphone designed for immersive music, calls, and modern everyday listening.",
  },
  {
    id: 4,
    name: "Noise Two Wireless",
    slug: "noise-two-wireless",
    brand: "Noise",
    mainCategory: "Wireless",
    subCategory: "Over-Ear",
    price: 2499,
    originalPrice: 3499,
    rating: 4.1,
    reviewCount: 612,
    stock: 16,
    featured: false,
    bestSeller: false,
    useCase: ["Calls", "Daily Use"],
    noiseCancellation: false,
    batteryLife: "50h",
    connectivity: "Bluetooth 5.3",
    mic: true,
    color: "Green",
    image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=900&q=80",
    description: "A premium headphone designed for immersive music, calls, and modern everyday listening.",
  },
  {
    id: 5,
    name: "OnePlus Bullets Wireless Z2",
    slug: "oneplus-bullets-wireless-z2",
    brand: "OnePlus",
    mainCategory: "Wireless",
    subCategory: "Neckband",
    price: 1999,
    originalPrice: 2299,
    rating: 4.4,
    reviewCount: 3075,
    stock: 30,
    featured: false,
    bestSeller: true,
    useCase: ["Calls", "Workout", "Daily Use"],
    noiseCancellation: false,
    batteryLife: "30h",
    connectivity: "Bluetooth 5.0",
    mic: true,
    color: "Black",
    image: "https://images.unsplash.com/photo-1578319439584-104c94d37305?auto=format&fit=crop&w=900&q=80",
    description: "A premium headphone designed for immersive music, calls, and modern everyday listening.",
  },
  {
    id: 6,
    name: "JBL C100SI",
    slug: "jbl-c100si",
    brand: "JBL",
    mainCategory: "Wired",
    subCategory: "In-Ear",
    price: 699,
    originalPrice: 1299,
    rating: 4.2,
    reviewCount: 5199,
    stock: 48,
    featured: false,
    bestSeller: true,
    useCase: ["Music", "Calls"],
    noiseCancellation: false,
    batteryLife: "N/A",
    connectivity: "3.5mm Jack",
    mic: true,
    color: "Red",
    image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80",
    description: "A premium headphone designed for immersive music, calls, and modern everyday listening.",
  },
  {
    id: 7,
    name: "Sony MDR-ZX110A",
    slug: "sony-mdr-zx110a",
    brand: "Sony",
    mainCategory: "Wired",
    subCategory: "On-Ear",
    price: 999,
    originalPrice: 1490,
    rating: 4.1,
    reviewCount: 2014,
    stock: 19,
    featured: false,
    bestSeller: false,
    useCase: ["Music", "Daily Use"],
    noiseCancellation: false,
    batteryLife: "N/A",
    connectivity: "3.5mm Jack",
    mic: false,
    color: "White",
    image: "https://images.unsplash.com/photo-1519677100203-a0e668c92439?auto=format&fit=crop&w=900&q=80",
    description: "A premium headphone designed for immersive music, calls, and modern everyday listening.",
  },
  {
    id: 8,
    name: "boAt BassHeads 100",
    slug: "boat-bassheads-100",
    brand: "boAt",
    mainCategory: "Wired",
    subCategory: "In-Ear",
    price: 499,
    originalPrice: 999,
    rating: 4.0,
    reviewCount: 8400,
    stock: 55,
    featured: false,
    bestSeller: true,
    useCase: ["Music", "Calls"],
    noiseCancellation: false,
    batteryLife: "N/A",
    connectivity: "3.5mm Jack",
    mic: true,
    color: "Black",
    image: "https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?auto=format&fit=crop&w=900&q=80",
    description: "A premium headphone designed for immersive music, calls, and modern everyday listening.",
  },
  {
    id: 9,
    name: "Redgear Cosmo 7.1",
    slug: "redgear-cosmo-7-1",
    brand: "Redgear",
    mainCategory: "Wired",
    subCategory: "Gaming Headset",
    price: 1799,
    originalPrice: 2999,
    rating: 4.3,
    reviewCount: 1521,
    stock: 9,
    featured: true,
    bestSeller: false,
    useCase: ["Gaming", "Calls"],
    noiseCancellation: false,
    batteryLife: "N/A",
    connectivity: "USB / 3.5mm",
    mic: true,
    color: "Black",
    image: "https://images.unsplash.com/photo-1612444530582-fc66183b16f7?auto=format&fit=crop&w=900&q=80",
    description: "A premium headphone designed for immersive music, calls, and modern everyday listening.",
  },
  {
    id: 10,
    name: "EKSA E900 Pro",
    slug: "eksa-e900-pro",
    brand: "EKSA",
    mainCategory: "Wired",
    subCategory: "Gaming Headset",
    price: 2399,
    originalPrice: 3499,
    rating: 4.4,
    reviewCount: 611,
    stock: 5,
    featured: true,
    bestSeller: false,
    useCase: ["Gaming", "Streaming"],
    noiseCancellation: false,
    batteryLife: "N/A",
    connectivity: "3.5mm Jack",
    mic: true,
    color: "Black / Blue",
    image: "https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=900&q=80",
    description: "A premium headphone designed for immersive music, calls, and modern everyday listening.",
  },
];

export const featuredProducts = products.filter((product) => product.featured);
export const wirelessProducts = products.filter(
  (product) => product.mainCategory === "Wireless"
);
export const wiredProducts = products.filter(
  (product) => product.mainCategory === "Wired"
);
